# 设备和应用配置
device:
  platformName: Android
  platformVersion: "12"
  deviceName: MuMu12
  noReset: True
  automationName: UiAutomator2
  
app:
  appPackage: com.game.sanguo
  appActivity: com.cocos.game.AppActivity
  
# Appium服务器配置
server:
  host: 127.0.0.1
  port: 4723